# Generated by Django 4.1.3 on 2022-11-24 13:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('class_name', models.CharField(choices=[('Short_game', 'Short_game'), ('Kids_club', 'Kids_club'), ('Long_game', 'Long_game')], max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Fully_Booked', 'Fully_Booked'), ('Available', 'Available')], default='Available', max_length=15)),
                ('places', models.IntegerField(default=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('requested_date', models.DateField()),
                ('bookingtatus', models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('p', 'Pending')], default='p', max_length=10)),
                ('class_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='golf.classname')),
                ('customer', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='golf.customer')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
