# Generated by Django 4.1.3 on 2022-11-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_name',
            new_name='full_name',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='ClassName',
        ),
    ]
