# Generated by Django 4.1.3 on 2022-11-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_alter_booking_class_name_alter_booking_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
    ]
