# Generated by Django 4.1.3 on 2022-11-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_rename_user_name_customer_full_name_delete_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('classes', models.CharField(choices=[('Short_game', 'Short_game'), ('Kids_club', 'Kids_club'), ('Long_game', 'Long_game')], max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
