# Generated by Django 4.1.3 on 2022-11-15 15:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_classname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Fully_Booked', 'Fully_Booked'), ('Availble', 'Availble')], default='Available', max_length=15)),
                ('seats', models.IntegerField(default=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('requested_date', models.DateField()),
                ('bookingtatus', models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('p', 'Pending')], default='p', max_length=10)),
                ('class_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='golf.classname')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='golf.customer')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
