# Generated by Django 4.1.3 on 2022-11-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
    ]
