# Generated by Django 4.1.3 on 2022-11-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('class_name', models.CharField(choices=[('Short_game', 'Short_game'), ('Kids_club', 'Kids_club'), ('Long_game', 'Long_game')], max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
