# Generated by Django 4.1.3 on 2022-11-16 20:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0008_classname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[(0, 'Fully_Booked'), (1, 'Availble')], default='Available', max_length=15)),
                ('places', models.IntegerField(default=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('class_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='golf.classname')),
                ('customer', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='golf.customer')),
            ],
        ),
    ]
