# Generated by Django 4.1.3 on 2022-11-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0009_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Fully_Booked', 'Fully_Booked'), ('Available', 'Available')], default='Available', max_length=15),
        ),
    ]
