# Generated by Django 4.1.3 on 2022-11-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0016_alter_booking_requested_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingtatus',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('p', 'Pending')], default='p', max_length=10),
        ),
    ]
