# Generated by Django 4.1.3 on 2022-11-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0017_booking_bookingtatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='requested_date',
            field=models.DateField(),
        ),
    ]
